name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: FinalAttemptDB
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install specific versions to avoid compatibility issues
        pip install Flask==2.0.1
        pip install Flask-SQLAlchemy==2.5.1
        pip install Flask-Login==0.5.0
        pip install Flask-WTF==0.15.1
        pip install WTForms==2.3.3
        pip install psycopg2-binary==2.9.1
        pip install pytest==6.2.5
        pip install email_validator==1.1.3
        pip install Werkzeug==2.0.1
        pip install Flask-Migrate==3.1.0
        pip install python-dotenv==0.19.0

    - name: Verify flask-wtf installation
      run: |
        python -c "import flask_wtf; print('flask_wtf is installed')"

    - name: Run tests
      env:
        DATABASE_URL: postgresql://postgres:admin@localhost:5432/FinalAttemptDB
        FLASK_ENV: testing
        SECRET_KEY: your-test-secret-key
      run: |
        pytest tests/test_app.py -v