name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: new_password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install flask-sqlalchemy
        pip install flask-login
        pip install flask-wtf
        pip install psycopg2-binary
        pip install pytest
        pip install email_validator

    - name: Run tests
      env:
        DATABASE_URL: postgresql://postgres:new_password@localhost:5432/postgres
      run: |
        pytest tests/test_app.py -v 